# Generated by Django 4.0.5 on 2022-07-07 16:42

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FoodList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('Noodles', 'Noodles'), ('Sandwich', 'Sandwich'), ('Chicken', 'Chicken'), ('Dimsum', 'Dimsum'), ('Pastry', 'Pastry'), ('Dessert', 'Dessert'), ('Drinks', 'Drinks')], default='Dimsum', max_length=100)),
                ('itemname', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('minpax', models.IntegerField(default=25)),
                ('price', models.IntegerField()),
                ('chosen', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('delivery_time', models.TimeField(default='19:00')),
                ('pax', models.IntegerField(default=25)),
                ('delivery_place', models.CharField(default='79 Anson Road', max_length=200)),
                ('delivery_date', models.DateField(default=datetime.date.today)),
            ],
        ),
    ]
