# Generated by Django 4.0.5 on 2022-07-06 09:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FoodList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('Noodles', 'Noodles'), ('Sandwich', 'Sandwich'), ('Chicken', 'Chicken'), ('Dimsum', 'Dimsum'), ('Pastry', 'Pastry'), ('Dessert', 'Dessert'), ('Drinks', 'Drinks')], default='Dimsum', max_length=100)),
                ('itemname', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('minpax', models.IntegerField(default=25)),
                ('price', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Todo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=100)),
                ('details', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('foodlist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='warehouse.foodlist')),
            ],
        ),
    ]
