# Generated by Django 4.0.5 on 2022-07-07 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='pax',
            field=models.IntegerField(default=25),
        ),
    ]
