# Generated by Django 4.0.5 on 2022-07-07 06:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='menu',
            name='chosen',
            field=models.BooleanField(default=False),
        ),
    ]
