# Generated by Django 4.0.5 on 2022-07-06 02:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse', '0003_menu'),
    ]

    operations = [
        migrations.AddField(
            model_name='menu',
            name='minpax',
            field=models.IntegerField(default=25),
        ),
        migrations.AddField(
            model_name='menu',
            name='price',
            field=models.IntegerField(default=10),
        ),
    ]
