# Generated by Django 4.0.5 on 2022-07-08 08:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse', '0003_order_menu'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='menu',
            name='chosen',
        ),
    ]
