# Generated by Django 4.0.5 on 2022-07-12 06:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse', '0005_alter_foodlist_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='Logistics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('logscategory', models.CharField(max_length=100)),
                ('logsname', models.CharField(max_length=100)),
                ('logsdescription', models.CharField(max_length=100)),
                ('logsquantity', models.IntegerField(default=0)),
                ('logsprice', models.DecimalField(decimal_places=2, max_digits=6)),
                ('logslimit', models.IntegerField(default=0)),
            ],
        ),
    ]
