# Generated by Django 4.0.5 on 2022-07-06 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse', '0008_alter_foodlist_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='foodlist',
            name='category',
            field=models.CharField(choices=[('Noodles', 'Noodles'), ('Sandwich', 'Sandwich'), ('Chicken', 'Chicken'), ('Dimsum', 'Dimsum'), ('Pastry', 'Pastry'), ('Dessert', 'Dessert'), ('Drinks', 'Drinks')], default='Dimsum', max_length=100),
        ),
    ]
