# Generated by Django 4.0.5 on 2022-07-12 14:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse', '0008_logistics_perpkt'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrdertoLogistics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('logistics', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='warehouse.logistics')),
                ('orders', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='warehouse.order')),
            ],
        ),
    ]
