# Generated by Django 4.0.5 on 2022-07-06 08:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse', '0009_alter_foodlist_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='category',
        ),
        migrations.RemoveField(
            model_name='order',
            name='itemname',
        ),
        migrations.AddField(
            model_name='order',
            name='foodlist',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='warehouse.foodlist'),
            preserve_default=False,
        ),
    ]
