# Generated by Django 4.0.5 on 2022-07-12 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse', '0009_ordertologistics'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordertologistics',
            name='logsneeded',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
