# Generated by Django 4.0.5 on 2022-07-12 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse', '0010_ordertologistics_logsneeded'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='logs_confirmed',
            field=models.BooleanField(default=False),
        ),
    ]
